name: daassets_example
description: Example code for the daassets library.
version: 1.1.0
homepage: https://github.com/mauriciotogneri/daassets

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

flutter:

  assets:

    # icons
    - assets/icon/

    # images
    - assets/image/