name: daassets_example
description: Example code for the daassets library.
version: 1.5.0
homepage: https://github.com/mauriciotogneri/daassets

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:

  flutter:
    sdk: flutter

flutter:

  assets:
    - assets/icon/
    - assets/image/
    - assets/text/