name: daassets
description: A Dart package to automatically generate a class containing references to all assets in your project.
version: 1.3.0
homepage: https://github.com/mauriciotogneri/daassets

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  yaml: ^2.2.1